//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IDivide")]
    public interface IDivide {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDivide/DivideNumbers", ReplyAction="http://tempuri.org/IDivide/DivideNumbersResponse")]
        int DivideNumbers(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDivide/DivideNumbers", ReplyAction="http://tempuri.org/IDivide/DivideNumbersResponse")]
        System.Threading.Tasks.Task<int> DivideNumbersAsync(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDivideChannel : ConsoleClient.ServiceReference.IDivide, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DivideClient : System.ServiceModel.ClientBase<ConsoleClient.ServiceReference.IDivide>, ConsoleClient.ServiceReference.IDivide {
        
        public DivideClient() {
        }
        
        public DivideClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DivideClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DivideClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DivideClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int DivideNumbers(int a, int b) {
            return base.Channel.DivideNumbers(a, b);
        }
        
        public System.Threading.Tasks.Task<int> DivideNumbersAsync(int a, int b) {
            return base.Channel.DivideNumbersAsync(a, b);
        }
    }
}
